version: "3.8"
services:
  etaxidb:
    image: postgres:13
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - ./postgres/init/:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_DB: etaxi
      POSTGRES_USER: etaxi
      POSTGRES_PASSWORD: etaxi
      PGDATA: /var/lib/postgresql/data/etaxi
    networks:
      - backend

networks:
  backend:
volumes:
  my-db: